matrix:
- name: Markdown files
  aspell:
    lang: en
    d: en_GB
  dictionary:
    wordlists:
    - .wordlist.txt
    output: .wordlist.dic
  sources:
  - ./**/*.md|!./index.md|!./README.md
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - markdown.extensions.fenced_code
      - markdown.extensions.admonition
  - pyspelling.filters.url:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - code
      - pre
